select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} termostat lås"
    id: thermostat_lock_channel_24
    address: 2420
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} mode"
    id: mode_channel_24
    register_type: read
    address: 2402
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} temperatur"
    id: temperatur_channel_24
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 2404
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} floor temperature"
    id: floor_temperature_channel_24
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 2405
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} desired temperature"
    id: desired_temperature_channel_24
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 2401
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} luftfugtighed"
    id: luftfugtighed_channel_24
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 2406
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} dugpunkt"
    id: dugpunkt_channel_24
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 2407
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} temperatur setpunkt"
    id: temperatur_setpunkt_channel_24
    min_value: 6.0
    max_value: 30.0
    step: 0.5
    address: 2419
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_24} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_24
    min_value: 6.0
    max_value: 30.0
    step: 0.5
    address: 2422
    force_new_range: true
    use_write_multiple: true 
    multiply: 100


#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_24}"
    id: sentio_warning_channel_24
    register_type: read
    address: 2401
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_24}"
    id: sentio_battery_low_channel_24
    register_type: read
    address: 2403
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_24}
    current_temp_sensor_id: temperatur_channel_24
    target_temp_sensor_id: temperatur_setpunkt_channel_24
    mode_select_id: mode_channel_24

