select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} termostat lås"
    id: thermostat_lock_channel_19
    address: 1920
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} mode"
    id: mode_channel_19
    register_type: read
    address: 1902
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} temperatur"
    id: temperatur_channel_19
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1904
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} floor temperature"
    id: floor_temperature_channel_19
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1905
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} desired temperature"
    id: desired_temperature_channel_19
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1901
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} luftfugtighed"
    id: luftfugtighed_channel_19
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1906
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} dugpunkt"
    id: dugpunkt_channel_19
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1907
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} temperatur setpunkt"
    id: temperatur_setpunkt_channel_19
    min_value: 6.0
    max_value: 30.0
    step: 0.5
    address: 1919
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_19} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_19
    min_value: 6.0
    max_value: 30.0
    step: 0.5
    address: 1922
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_19}"
    id: sentio_warning_channel_19
    register_type: read
    address: 1901
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_19}"
    id: sentio_battery_low_channel_19
    register_type: read
    address: 1903
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_19}
    current_temp_sensor_id: temperatur_channel_19
    target_temp_sensor_id: temperatur_setpunkt_channel_19
    mode_select_id: mode_channel_19

