select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_21} termostat lås"
    id: thermostat_lock_channel_21
    address: 2120
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_21} mode"
    id: mode_channel_21
    register_type: read
    address: 2102
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_21} temperatur"
    id: temperatur_channel_21
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 2104
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_21} luftfugtighed"
    id: luftfugtighed_channel_21
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 2106
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_21} dugpunkt"
    id: dugpunkt_channel_21
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 2107
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_21} temperatur setpunkt"
    id: temperatur_setpunkt_channel_21
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 2119
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_21} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_21
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 2122
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_21}"
    id: sentio_warning_channel_21
    register_type: read
    address: 2101
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_21}"
    id: sentio_battery_low_channel_21
    register_type: read
    address: 2103
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_21}
    current_temp_sensor_id: temperatur_channel_21
    target_temp_sensor_id: temperatur_setpunkt_channel_21
    mode_select_id: mode_channel_21

