select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} termostat lås"
    id: thermostat_lock_channel_23
    address: 2320
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} mode"
    id: mode_channel_23
    register_type: read
    address: 2302
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} temperatur"
    id: temperatur_channel_23
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 2304
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} floor temperature"
    id: floor_temperature_channel_23
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 2305
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} desired temperature"
    id: desired_temperature_channel_23
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 2301
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} luftfugtighed"
    id: luftfugtighed_channel_23
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 2306
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} dugpunkt"
    id: dugpunkt_channel_23
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 2307
    filters:
      - multiply: 0.01
      - lambda: |-
          return roundf(x * 10.0f) / 10.0f;

#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} temperatur setpunkt"
    id: temperatur_setpunkt_channel_23
    min_value: 6.0
    max_value: 30.0
    step: 0.5
    address: 2319
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_23} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_23
    min_value: 6.0
    max_value: 30.0
    step: 0.5
    address: 2322
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_23}"
    id: sentio_warning_channel_23
    register_type: read
    address: 2301
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_23}"
    id: sentio_battery_low_channel_23
    register_type: read
    address: 2303
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_23}
    current_temp_sensor_id: temperatur_channel_23
    target_temp_sensor_id: temperatur_setpunkt_channel_23
    mode_select_id: mode_channel_23

